// Dados completos dos 16 carrosséis com imagens
export const carouselsData = [
  {id:1,name:"Quem Somos",folder:"01 - CARROSEL QUEM SOMOS",description:"Apresentação institucional com múltiplas variações (32 imagens)",slides:["Carrosel  quem eh uzzai2.png","Carrosel.png","Gemini_Generated_Image_21cw2c21cw2c21cw.png","Gemini_Generated_Image_2ifbap2ifbap2ifb (1).png","Gemini_Generated_Image_2ifbap2ifbap2ifb.png","Gemini_Generated_Image_4oltpc4oltpc4olt.png","Gemini_Generated_Image_6qorla6qorla6qor.png","Gemini_Generated_Image_7a4w7c7a4w7c7a4w.png","Gemini_Generated_Image_g0m5zsg0m5zsg0m5 (1).png","Gemini_Generated_Image_g0m5zsg0m5zsg0m5.png","Gemini_Generated_Image_jl0g9hjl0g9hjl0g (1).png","Gemini_Generated_Image_jl0g9hjl0g9hjl0g.png","Gemini_Generated_Image_maqnbxmaqnbxmaqn.png","Gemini_Generated_Image_njs70tnjs70tnjs7.png","Gemini_Generated_Image_nkbzhxnkbzhxnkbz.png","Gemini_Generated_Image_ohj29mohj29mohj2.png","Gemini_Generated_Image_uywalhuywalhuywa.png","Gemini_Generated_Image_vk4vxwvk4vxwvk4v.png","Gemini_Generated_Image_vt2wirvt2wirvt2w.png","INSTA 0.png","INSTA 0.png.png","INSTA 1.png.png","Screenshot_2.png","Screenshot_4.png","Screenshot_5.png","Screenshot_6.png","Screenshot_7.png","Screenshot_8.png","Screenshot_9.png","carrosel (2).png","carrosel (3).png","carrosel completo.png"],category:"Institucional",quality:4,fileSize:"Variado",bestFor:["Instagram","LinkedIn"]},
  {id:2,name:"O que é o UzzApp",folder:"02 - Carrosel o que é o uzzapp",description:"Explicação do produto UzzApp (17 variações)",slides:["1 (2).png","1.png","2 (2).png","2 (3).png","2.png","3 (2).png","3.png","4.png","5 (2).png","5 (3).png","5.png","6 (2).png","6 (3).png","6.png","66.png","666 (2).png","666.png"],category:"Produto",quality:4,fileSize:"Variado",bestFor:["Apresentações","Site"]},
  {id:3,name:"Como Usar IA (Versão 5)",folder:"03 -  CARROSSEL 05 COMO USAR IA NA SUA EMPRESA",description:"Guia educacional sobre IA em empresas (22 slides)",slides:["1 (1).png","1 (2).png","1 (3).png","2 (1).png","2 (2).png","2 (3).png","3 (1).png","3 (2).png","4 (1).png","4 (2).png","5 (1).png","5 (2).png","5 (3).png","6 (1).png","6 (2).png","7 (1).png","7 (2).png","7 (3).png","Gemini_Generated_Image_bt7gx5bt7gx5bt7g.png","Gemini_Generated_Image_bz1p4kbz1p4kbz1p.png","Gemini_Generated_Image_fw6hy1fw6hy1fw6h.png","Gemini_Generated_Image_jndac5jndac5jnda.png"],category:"Educacional",quality:4,fileSize:"Variado",bestFor:["LinkedIn","Blog"]},
  {id:4,name:"Como Usar IA na Empresa",folder:"04 - COMO USAR IA NA SUA EMPRESA",description:"Guia prático de implementação de IA (23 slides)",slides:["1 (1).png","1 (2).png","1 (3).png","2 (1).png","2 (2).png","2 (3).png","2 (4).png","3 (1).png","3 (2).png","3 (3).png","4 (1).png","4 (2).png","4 (3).png","4 (4).png","5 (1).png","5 (2).png","5 (3).png","6 (1).png","6 (2).png","6 (3).png","6 (4).png","Gemini_Generated_Image_ijytgijytgijytgi.png","Gemini_Generated_Image_tjtholtjtholtjth (1).png"],category:"Educacional",quality:4,fileSize:"Variado",bestFor:["LinkedIn","Blog"]},
  {id:5,name:"Processo UzzApp",folder:"05 - Carrosel Processo UzzApp",description:"Fluxo de implementação do UzzApp (23 variações)",slides:["1 (1).png","1 (2).png","1 (3).png","1 (4).png","1 (5).png","1 (6).png","1 (7).png","2 (1).png","2 (2).png","2 (3).png","2 (4).png","3 (1).png","3 (2).png","3 (3).png","4 (1).png","4 (2).png","5 (1).png","5 (2).png","5 (3).png","5 (4).png","5 (5).png","5 (6).png","5 (7).png"],category:"Produto",quality:4,fileSize:"Variado",bestFor:["Apresentações","Site"]},
  {id:6,name:"Quem é UzzAi (Variação B)",folder:"06 - CAROUSEL-4-QUEM-E-UZZAI-VARB",description:"Versão focada em diferenciação (6 slides)",slides:["uzzai_slide_1_capa_identidade_1769546750138.png","uzzai_slide_2_missao_1769546773816.png","uzzai_slide_3_human_in_loop_1769546794252.png","uzzai_slide_4_produtos_solucoes_1769546819814.png","uzzai_slide_5_diferenciais_1769546840922.png","uzzai_slide_6_cta_variacao_b_1769546864988.png"],category:"Institucional",quality:5,fileSize:"~650 KB",bestFor:["Instagram","Stories"]},
  {id:7,name:"UzzAi - Quem Somos (Completo)",folder:"07 - CAROUSEL-UZZAI-QUEM-SOMOS",description:"Apresentação institucional completa (4 opções de capa + 6 slides)",slides:["slide_1_opcao_1_liberdade_1769546185824.png","slide_1_opcao_2_automacao_1769546214496.png","slide_1_opcao_3_humanizacao_1769546234753.png","slide_1_opcao_4_resultados_1769546254568.png","slide_2_origem_uzguri_1769546273189.png","slide_3_missao_1769546291721.png","slide_4_produtos_ecossistema_1769546312246.png","slide_5_time_equipe_1769546330084.png","slide_6_diferenciais_porque_1769546349114.png","slide_7_cta_proximo_passo_1769546367859.png"],category:"Institucional",quality:5,fileSize:"~600 KB",bestFor:["Instagram","Stories","Feed"]},
  {id:8,name:"Carrossel Primeiro",folder:"08 - CARROSEL PRIMEIRO",description:"Primeira versão institucional (12 variações)",slides:["1 (1).png","1 (2).png","1 (3).png","1 (4).png","1.png","2 (1).png","2 (2).png","3 (1).png","3 (2).png","4.png","5.png","6.png"],category:"Geral",quality:4,fileSize:"Variado",bestFor:["Instagram","Stories"]},
  {id:9,name:"Timeline | Antes e Depois",folder:"10 -estilo-1-timeline",description:"Design de timeline mostrando evolução (4 variações)",slides:["var1-atendimento-noturno.png","var2-perda-vendas.png","var3-24-7-vs-comercial.png","var4-impacto-financeiro.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:10,name:"Comparação | Lado a Lado",folder:"11 - estilo-2-comparacao",description:"Comparações visuais impactantes (4 variações)",slides:["var1-chatbot-comparacao.png","var2-manual-vs-automatizado.png","var3-features-basicas-vs-avancadas.png","var4-roi-comparacao.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:11,name:"Flowchart | Processos",folder:"14 - estilo-3-flowchart",description:"Fluxogramas e processos visuais (4 variações)",slides:["var1-split-pix-automatico.png","var2-processo-implementacao.png","var3-fluxo-atendimento.png","var4-integracao-sistemas.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:12,name:"Tech | Fundo Código",folder:"15 - estilo-4-codigo",description:"Design tecnológico com elementos de código (4 variações)",slides:["var1-clinica-piloto-automatico.png","var2-ia-conversa-humano.png","var3-automacao-processos.png","var4-tecnologia-ia.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:13,name:"HUD Premium | Futurista",folder:"17 - ESTILO-5-HUD-PREMIUM",description:"Interface premium com elementos HUD (4 variações)",slides:["var1-quem-e-uzzai.png","var2-features-cards.png","var3-beneficios-destaque.png","var4-identidade-premium.png"],category:"Design",quality:4,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:14,name:"Depoimentos | Social Proof",folder:"18 - estilo-6-depoimentos",description:"Cases e depoimentos de clientes (4 variações)",slides:["var1-depoimento-clinica.png","var2-metricas-impacto.png","var3-antes-depois-cliente.png","var4-galeria-clientes.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:15,name:"Infográfico | Dados e Stats",folder:"19 - estilo-7-infografico",description:"Visualização de dados e estatísticas (4 variações)",slides:["var1-stats-mercado.png","var2-comparacao-custos.png","var3-jornada-numeros.png","var4-tempo-economizado.png"],category:"Design",quality:3,fileSize:"Otimizado",bestFor:["Instagram","Stories"]},
  {id:16,name:"Tutorial | Passo a Passo",folder:"20 - estilo-8-tutorial",description:"Guias práticos e tutoriais (4 variações)",slides:["var1-3-passos-simples.png","var2-checklist-implementacao.png","var3-fluxo-configuracao.png","var4-guia-rapido-uso.png"],category:"Educacional",quality:3,fileSize:"Otimizado",bestFor:["LinkedIn","Blog"]}
];
